data = [
"Christmas Tree,Evergreen, Decorate, Holiday, Pine, Ornaments",
"Santa Claus,North Pole, Sleigh, Red, Beard, Reindeer",
"Reindeer,Antlers, Santa, Sleigh, Fly, Rudolph",
"Snowflakes,White, Winter, Cold, Fall, Ice",
"Gingerbread House,Candy, Build, Christmas, Sweet, Cookies",
"Stocking,Fireplace, Stuff, Hang, Santa, Gifts",
"Presents,Gift, Wrap, Christmas, Surprise, Ribbon",
"Holiday Lights,Bright, Colorful, Christmas, Decorate, Tree",
"Candy Cane,Red, White, Stripes, Sweet, Mint",
"Eggnog,Drink, Holiday, Creamy, Alcohol, Christmas",
"Caroling,Sing, Songs, Christmas, Door, Joy",
"Christmas Eve,Night, Before, Santa, December, 24th",
"Rudolph,Reindeer, Red, Nose, Santa, Lead",
"Christmas Carol,Song, Sing, Holiday, Joy, Music",
"Nativity Scene,Jesus, Birth, Mary, Joseph, Manger",
"Wreath,Door, Circle, Green, Decorate, Christmas",
"Elves,Santa, Workshop, Helpers, Small, Gifts",
"North Pole,Santa, Arctic, Cold, Workshop, Elves",
"Christmas Spirit,Cheer, Joy, Holiday, Merry, Festive",
"Holly,Red, Berries, Green, Plant, Christmas",
"Ornaments,Decorate, Hang, Tree, Ball, Christmas",
"Chimney,Fireplace, Santa, Roof, Smoke, House",
"Silent Night,Song, Christmas, Carol, Holy, Peace",
"Wrapping Paper,Cover, Gifts, Presents, Tape, Ribbon",
"Christmas Morning,Open, Gifts, Excitement, December, 25th",
"Snowman,Frosty, Winter, Cold, Build, Snow",
"Frosty,Snowman, Hat, Magic, Winter, Cold",
"Mistletoe,Kiss, Green, Hang, Plant, Tradition",
"Jingle Bells,Song, Sleigh, Ride, Carol, Ring",
"Peppermint,Candy, Mint, Christmas, Sweet, Red",
"Christmas Card,Send, Mail, Holiday, Greeting, Family",
"Hot Chocolate,Drink, Warm, Cocoa, Winter, Marshmallows",
"Gift Exchange,Present, Swap, Secret, Christmas, Give",
"Snowball Fight,Winter, Throw, Cold, Snow, Fun",
"Yule Log,Wood, Fire, Tradition, Cake, Christmas",
"Holiday Party,Celebration, Christmas, Gather, Friends, Festive",
"Chestnuts,Roasting, Fire, Warm, Christmas, Nut",
"Christmas Cookies,Bake, Sweet, Holiday, Treat, Frosting",
"Scarf,Neck, Warm, Winter, Wear, Cold",
"Snow Globe,Shake, Scene, Winter, Glass, Christmas",
"Christmas Countdown,Days, Calendar, Advent, Holiday, Waiting",
"Poinsettia,Red, Flower, Plant, Holiday, Christmas",
"Christmas Star,Bethlehem, Top, Tree, Bright, Symbol",
"Bells,Ring, Jingle, Sound, Christmas, Music",
"Mulled Wine,Warm, Spices, Drink, Holiday, Alcohol",
"Holiday Baking,Sweet, Oven, Cookies, Christmas, Treats",
"Gift Wrapping,Paper, Presents, Tape, Bow, Christmas",
"New Year's Eve,December, 31st, Countdown, Celebrate, Fireworks",
"Nutcracker,Ballet, Christmas, Toy, Soldier, Clara",
"Christmas Sweater,Ugly, Holiday, Warm, Knit, Winter",
"Ice Skating,Winter, Rink, Blade, Snow, Glide",
"Sleigh Ride,Santa, Reindeer, Snow, Winter, Travel",
"Holiday Market,Shopping, Christmas, Stalls, Gifts, Decor",
"Gift Box,Present, Wrap, Surprise, Ribbon, Bow",
"Christmas Pajamas,Sleep, Cozy, Holiday, Wear, Morning",
"Holiday Wreath,Decorate, Door, Green, Christmas, Circle",
"Three Wise Men,Magi, Gifts, Nativity, Jesus, Gold",
"Holiday Candle,Light, Scented, Flame, Christmas, Decor",
"Elf on the Shelf,Toy, Move, Santa, Watch, Kids",
"Snow Boots,Winter, Wear, Feet, Cold, Outdoor",
"Pinecones,Tree, Decor, Nature, Brown, Winter",
"Icicles,Freeze, Water, Roof, Hang, Cold",
"Holiday Dinner,Feast, Family, Christmas, Table, Food",
"Santa’s Workshop,Elves, North Pole, Gifts, Toys, Build",
"Winter Wonderland,Snow, White, Landscape, Christmas, Magic",
"Garland,Decorate, Tree, Green, Holiday, String",
"Christmas Countdown,Days, Calendar, Advent, Holiday, Excitement",
"Skiing,Snow, Sport, Winter, Mountain, Poles",
"Fuzzy Mittens,Warm, Hands, Winter, Cold, Wear",
"Holiday Parade,Christmas, Floats, March, Crowd, Celebrate",
"Gift Tag,Present, Label, Write, Name, Attach",
"Santa’s Hat,Red, White, Wear, Christmas, Beard",
"Jack Frost,Winter, Cold, Ice, Freeze, Myth",
"Fireplace,Warm, Wood, Heat, Fire, Cozy",
"Snow Angel,Winter, Lie, Ground, Shape, Snow",
"Ice Sculpture,Carve, Cold, Winter, Display, Art",
"Christmas Cookie Swap,Exchange, Bake, Sweet, Holiday, Friends",
"Reindeer Antlers,Head, Rudolph, Wear, Costume, Christmas",
"Nutmeg,Spice, Eggnog, Holiday, Warm, Flavor",
"Silent Night,Song, Christmas, Peace, Carol, Holy",
"White Christmas,Snow, Winter, Dream, Movie, Classic",
"Peppermint Bark,Candy, Sweet, Chocolate, Holiday, Crunch",
"Christmas Miracle,Wonder, Holiday, Surprise, Spirit, Magic",
"Ski Lodge,Winter, Mountain, Cozy, Snow, Cabin",
"Ugly Sweater,Christmas, Knit, Wear, Party, Silly",
"Hot Toddy,Drink, Warm, Whiskey, Holiday, Cozy",
"Fleece Blanket,Warm, Soft, Cozy, Winter, Snuggle",
"Snowball,Throw, Cold, Fight, Winter, White",
"Holiday Shopping,Gifts, Store, Buy, Presents, Mall",
"Advent Calendar,Days, December, Chocolate, Countdown, Open",
"Christmas Classic,Movie, Song, Holiday, Tradition, Beloved",
"Tree Topper,Star, Angel, Christmas, Decorate, Ornament",
"Sugar Cookies,Sweet, Bake, Christmas, Frost, Decorate",
"Santa's Sack,Gifts, Red, Bag, Presents, Deliver",
"Snowstorm,Blizzard, Winter, Cold, White, Storm",
"Yule Tradition,Holiday, Christmas, Ceremony, Log, Ancient",
"Toy Soldiers,Christmas, Nutcracker, March, Decorate, Military",
"Frosted Windows,Cold, Ice, Winter, Snow, Outside",
"Santa’s Beard,White, Face, Jolly, Red, Claus",
"Holiday Feast,Food, Christmas, Celebrate, Family, Dinner",
"Christmas Stocking,Hang, Gifts, Fireplace, Stuffed, Red",
"Kwanzaa,Celebration, African, December, Heritage, Holiday",
"Christmas Music,Songs, Holiday, Listen, Joyful, Caroling",
"Manger,Jesus, Nativity, Stable, Animals, Birth",
"Winter Solstice,December, Longest, Night, Celebrate, Season",
"Christmas Pageant,Show, Performance, Holiday, Kids, Nativity",
"Cinnamon,Spice, Bake, Sweet, Holiday, Warm",
"New Year’s Resolution,Goals, Change, January, Plan, Promise",
"Holiday Greetings,Cards, Send, Wishes, Celebrate, Merry",
"Christmas Eve Service,Church, Night, Caroling, Worship, Christmas",
"Frosty the Snowman,Snow, Winter, Character, Children, Hat",
"Christmas Traditions,Family, Celebrate, Holiday, Customs, History",
"Holiday Spirit,Cheer, Joy, Celebrate, Love, Giving",
"Twinkling Lights,Bright, Tree, Decorate, Holiday, Glow",
"Tinsel,Shiny, Tree, Decorate, Silver, Holiday",
"Christmas Morning,Gifts, Excitement, Family, Open, December",
"Holiday Cookies,Bake, Sweet, Decorate, Treats, Christmas",
"Cocoa,Hot, Chocolate, Drink, Winter, Marshmallows",
"Secret Santa,Gifts, Exchange, Surprise, Holiday, Fun",
"Christmas Party,Celebrate, Friends, Food, Fun, Holiday",
"Candlelight Service,Church, Christmas, Light, Worship, Evening",
"Snowy Night,Winter, White, Cold, Quiet, Stars",
"Christmas Village,Display, Miniature, Holiday, Decorate, Scene",
"Nutcracker Ballet,Dance, Christmas, Performance, Music, Clara",
"Holiday Cheer,Joy, Spirit, Celebrate, Happy, Merry",
"Christmas Snow,White, Winter, Flakes, Cold, Scene",
"Ringing in the New Year,Celebrate, Midnight, Countdown, Fireworks, January",
"Santa’s List,Naughty, Nice, Children, Gifts, Check",
"Holiday Decorations,Ornament, Tree, Lights, Decorate, Festive",
"Merry Christmas,Greeting, Wishes, Happy, Holiday, Cheer",
"Christmas Joy,Happiness, Celebrate, Family, Spirit, Cheer",
"Kiss Under Mistletoe,Plant, Christmas, Tradition, Kiss, Couples",
"Holiday Baking,Cookies, Sweet, Treats, Oven, Family",
"Christmas Countdown,Advent, Calendar, Days, Prepare, Wait",
"Santa’s Little Helper,Elf, Assist, Gifts, Workshop, Christmas",
"Gift Giving,Presents, Exchange, Holiday, Surprise, Joy",
"Chilly Weather,Cold, Winter, Snow, Bundle, Coat",
"Christmas Tree Farm,Grow, Cut, Evergreen, Holiday, Decorate",
"Holiday Movies,Film, Watch, Family, Tradition, Christmas",
"Twelve Days of Christmas,Song, Gifts, Holiday, Tradition, December",
"Snowflakes Falling,Winter, White, Cold, Flurries, Snow",
"Christmas Bread,Bake, Sweet, Holiday, Treat, Recipe",
"Fireside,Warm, Cozy, Fire, Hearth, Relax",
"Holly Jolly,Merry, Christmas, Cheer, Joyful, Spirit",
"Twelve Months of Christmas,Year, Celebration, Holiday, Tradition, Month",
"Noel,Christmas, Song, Holiday, Celebrate, Joy",
"Christmas Morning Brunch,Food, Family, Breakfast, Celebrate, Feast",
"Frosty Nights,Cold, Winter, Snow, Clear, Stars",
"Holiday Adventure,Journey, Explore, Family, Fun, Travel",
"New Year's Celebration,Party, Countdown, Midnight, Fireworks, Toast",
"Christmas Cheer,Joy, Happiness, Celebrate, Spirit, Holiday",
"Snowman,Winter, Frosty, Snow, Build, Carrot",
"Jingle Bells,Song, Christmas, Sleigh, Ring, Cheer",
"Yule Log,Cake, Dessert, Christmas, Tradition, Celebration",
"Candy Cane,Sweet, Peppermint, Red, Stripe, Christmas",
"Nativity Scene,Jesus, Mary, Joseph, Manger, Christmas",
"Holiday Spirit,Cheer, Joy, Celebration, Giving, Merry",
"Winter Coat,Warm, Wear, Cold, Outerwear, Jacket",
"Christmas Movies,Film, Watch, Family, Tradition, Holiday",
"Singing Carols,Christmas, Joy, Music, Groups, Holiday",
"Gift Exchange,Give, Receive, Holiday, Presents, Surprise",
"Mistletoe Kiss,Plant, Christmas, Couples, Tradition, Romance",
"Red Nosed Reindeer,Rudolph, Santa, Sleigh, Christmas, Guide",
"Holiday Crafting,DIY, Create, Fun, Decorations, Family",
"Snow Globe,Decoration, Snow, Winter, Shake, Scene",
"Christmas Traditions,Customs, Family, Holiday, Celebrate, History",
"Family Gathering,Together, Celebrate, Holiday, Relatives, Food",
"Christmas Cards,Send, Mail, Wishes, Friends, Family",
"Christmas Potluck,Share, Food, Gather, Friends, Meal",
"Sledding,Snow, Fun, Hill, Slide, Winter",
"Holiday Magic,Wonder, Spirit, Christmas, Surprise, Joy",
"Frosty Breath,Cold, Air, Winter, Breathe, Chill",
"Santa’s Elves,Helpers, Workshop, Toys, Christmas, North Pole",
"Warm Cocoa,Drink, Chocolate, Sweet, Mug, Marshmallows",
"Holiday Feasting,Food, Gather, Celebrate, Dinner, Tradition",
"Christmas Eve,Night, Prepare, Gifts, Family, Celebration",
"Gingerbread House,Candy, Bake, Sweet, Decorate, Holiday",
"Tinsel Garland,Decorate, Shiny, Christmas, Tree, Silver",
"Ice Skating Rink,Winter, Sport, Glide, Skates, Fun",
"Caroling,Sing, Groups, Christmas, Joyful, Music",
"Holiday Feast,Dinner, Food, Family, Celebrate, Christmas",
"Christmas Joy,Happiness, Celebrate, Family, Spirit, Cheer",
"Noel Celebration,Christmas, Holiday, Joy, Gather, Tradition",
"Holiday Memories,Remember, Family, Celebrate, Tradition, Joy",
"Jolly Santa,Claus, Red, Merry, Gifts, Holiday",
"Baking Cookies,Sweet, Dough, Oven, Treats, Holiday",
"Warming Hearth,Fire, Cozy, Home, Heat, Relax",
"Holiday Show,Performance, Celebrate, Christmas, Family, Enjoy",
"Cheerful Giver,Generous, Holiday, Spirit, Joy, Kind",
"Frosted Tips,Cold, Winter, Snow, Ice, Chill",
"Holiday Lights,Bright, Decorate, Tree, Twinkling, Christmas",
"New Year's Eve Party,Celebrate, Countdown, Midnight, Fun, Friends",
"Festive Gatherings,Family, Friends, Celebrate, Food, Holiday",
"Jingle All the Way,Song, Christmas, Cheer, Bells, Fun",
"Holiday Wishlist,Gifts, Want, Christmas, List, Dreams",
"Christmas Star,Shine, Tree, Top, Decoration, Light",
"Merry and Bright,Cheer, Holiday, Joyful, Christmas, Light",
"Winter Festivities,Celebrate, Holiday, Events, Fun, Snow",
"Joyful Celebration,Happiness, Party, Gather, Christmas, Friends",
"Warm Wishes,Greetings, Holiday, Kind, Send, Friends",
]

formatted_data = [
    "[" + ", ".join(f'"{word.strip().upper()}"' for word in item.split(',')) + "]"
    for item in data
]

for line in formatted_data:
    print(line)
